/*oRDENAR LOS DATOS DE FORMA DESCENTENTE O ASCENDENTE*/
SELECT * FROM usuarios ORDER BY id DESC
SELECT * FROM usuarios ORDER BY id ASC

SELECT * FROM usuarios ORDER BY fecha DESC

/*SE PONE UN LIMITE A LOS ELEMENTOS MOSTRADOS*/
SELECT * FROM usuarios LIMIT 3;

SELECT * FROM usuarios LIMIT 0,3;

